# Generated by Django 3.0.6 on 2020-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20181125_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilelocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profilelocation',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profilesubscriptiongroup',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profilesubscriptiongroup',
            name='subscription_group',
        ),
        migrations.RemoveField(
            model_name='profiletopic',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profiletopic',
            name='topic',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin',
            new_name='social_media',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lgbtqa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='page',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='poc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='published',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='woman',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.DeleteModel(
            name='FeaturedTalk',
        ),
        migrations.DeleteModel(
            name='ProfileLocation',
        ),
        migrations.DeleteModel(
            name='ProfileSubscriptionGroup',
        ),
        migrations.DeleteModel(
            name='ProfileTopic',
        ),
    ]
