# Generated by Django 3.0.6 on 2020-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200528_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='submittable_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
