# Generated by Django 3.0.6 on 2020-05-28 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200528_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='address_notes',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='location',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='location',
            name='old_ward',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='location',
            name='property_description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='location',
            name='ward',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(25)]),
        ),
    ]
