# Generated by Django 3.0.6 on 2020-05-28 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200528_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='old_ward',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='ward',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(25)]),
        ),
    ]
