# Generated by Django 3.0.6 on 2020-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('In-Progress', 'In-Progress'), ('Withdrawn', 'Withdrawn'), ('Accpeted', 'Accpeted'), ('Declined', 'Declined')], default='New', max_length=20)),
                ('submittable_url', models.URLField()),
                ('submittable_id', models.CharField(max_length=128)),
                ('date_created', models.DateField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('organization_name', models.CharField(max_length=256)),
                ('organization_website', models.URLField()),
                ('is_archived', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
