# Generated by Django 3.0.6 on 2020-05-28 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200528_1344'),
        ('artworks', '0002_auto_20200528_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='core.Label'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='organization_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='organization_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='submittable_url',
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
