# Generated by Django 3.0.6 on 2020-05-28 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200528_1344'),
        ('artworks', '0003_auto_20200528_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='labels',
            field=models.ManyToManyField(to='core.Label'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
