# Generated by Django 3.0.6 on 2020-05-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200528_1555'),
        ('artworks', '0004_auto_20200528_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='artwork',
            name='partner',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='artwork',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Program'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
