# Generated by Django 3.0.6 on 2020-05-28 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_auto_20200528_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2012), django.core.validators.MinValueValidator(2030)]),
        ),
    ]
