# Generated by Django 3.0.6 on 2020-05-28 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200528_1555'),
        ('artworks', '0006_artwork_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='organization_website',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='status',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='submittable_id',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='submittable_url',
        ),
        migrations.AddField(
            model_name='artwork',
            name='airtable_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist_credit',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='artwork',
            name='uid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('In-Progress', 'In-Progress'), ('Withdrawn', 'Withdrawn'), ('Accpeted', 'Accpeted'), ('Declined', 'Declined')], default='New', max_length=20)),
                ('submittable_url', models.URLField(max_length=256)),
                ('submittable_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('organization_name', models.CharField(blank=True, max_length=256)),
                ('organization_website', models.URLField(blank=True)),
                ('is_archived', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('labels', models.ManyToManyField(to='core.Label')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.Submission'),
        ),
    ]
