# Generated by Django 3.0.6 on 2020-05-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_auto_20200528_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
