# Generated by Django 3.0.6 on 2020-05-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200528_2037'),
        ('artworks', '0008_auto_20200528_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
    ]
